[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
	256dpi/MQTT @ ^2.5.2
build_flags =
	-DWIFI_SSID=\"nares\"
	-DWIFI_PASSWORD=\"satuduatiga\"
	-DMQTT_BROKER=\"broker.hivemq.com\"
	-DMQTT_PORT=1883
	-DMQTT_USERNAME=\"\"
	-DMQTT_PASSWORD=\"\"
	-DDEVICE_ID=\"vestmicro-esp32-01\"
